const cuisineOptions = [
  { value: "italian", label: "Italian" },
  { value: "south-indian", label: "South Indian" },
  { value: "north-indian", label: "North Indian" },
  { value: "biriyani", label: "Biriyani" },
  { value: "chinese", label: "Chinese" },
  { value: "nepali", label: "Nepali" },
  { value: "gujrati", label: "Gujrati" },
  { value: "asian", label: "Asian" },
  { value: "thai", label: "Thai" },
  { value: "mexican", label: "Mexican" },
  { value: "bengali", label: "Bengali" },
  { value: "rajasthani", label: "Rajasthani" },
  { value: "kashmiri", label: "Kashmiri" },
  { value: "goan", label: "Goan" },
  { value: "punjabi", label: "Punjabi" },
  { value: "hyderabadi", label: "Hyderabadi" },
  { value: "kerala", label: "Kerala" },
  { value: "assamese", label: "Assamese" },
  { value: "odisha", label: "Odisha" },
  { value: "maharashtrian", label: "Maharashtrian" },
  { value: "malabari", label: "Malabari" },
  { value: "mediterranean", label: "Mediterranean" },
  { value: "american", label: "American" },
  { value: "arabian", label: "Arabian" },
  { value: "korean", label: "Korean" },
  { value: "lebanese", label: "Lebanese" },
  { value: "sushi", label: "Sushi" },
  { value: "french", label: "French" },
  { value: "mughlai", label: "Mughlai" },
  { value: "fastfood", label: "Fast Food" },
  { value: "continental", label: "Continental" },
];

const typesOptions = [
  { value: "finedining", label: "Fine Dining" },
  { value: "casualdining", label: "Casual Dining" },
  { value: "pizza", label: "Pizza" },
  { value: "qsr", label: "Qsr" },
  { value: "ethniccuisine", label: "Ethnic Cuisine" },
  { value: "cafe", label: "Cafe" },
  { value: "girfflat50", label: "Girf Flat 50" },
  { value: "pub", label: "Pub" },
  { value: "streetfood", label: "Street Food" },
  { value: "familystyle", label: "Family Style" },
  { value: "seafood", label: "Seafood" },
  { value: "bakery", label: "Bakery" },
  { value: "nightlife", label: "Nightlife" },
  { value: "foodtruck", label: "Food Truck" },
  { value: "girfbuffetdeals", label: "Girf Buffet Deals" },
  { value: "buffet", label: "Buffet" },
  { value: "vegan", label: "Vegan" },
  { value: "5star", label: "5 Star" },
];

const featureOptions = [
  { label: "Wifi", value: "Wifi" },
  { label: "Parking", value: "Parking" },
  { label: "Air Conditioning", value: "AC" },
  { label: "Pets Allowed", value: "PetsAllowed" },
  { label: "Outdoor Seating", value: "OutdoorSeating" },
  { label: "Cards Accepted", value: "CardsAccepted" },
  { label: "Wallet Accepted", value: "WalletAccepted" },
  { label: "Home Delivery", value: "HomeDelivery" },
  { label: "Valet Available", value: "ValetAvailable" },
  { label: "Roof Top", value: "RoofTop" },
  { label: "Full Bar Available", value: "FullBarAvailable" },
  { label: "Lift", value: "Lift" },
  { label: "Smoking Area", value: "SmokingArea" },
  { label: "Live Performance", value: "LivePerformance" },
  { label: "Live Screening", value: "LiveScreening" },
];

module.exports = {
  cuisineOptions,
  typesOptions,
  featureOptions,
};
